#!/bin/bash -e
# Regen Concrete5 MySQL user random password

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF_PATH=/var/www/concrete5/config
CONF=CONF_PATH+"site.php"
BACKUP=CONF+".backup"

mv $CONF_PATH/site.php $CONF_PATH/site.php.backup
grep -v "^\define('DB_PASSWORD" $CONF_PATH/site.php.backup > $CONF_PATH/site.php
echo "define('DB_PASSWORD', '"$PASSWORD"');" >> $CONF_PATH/site.php

$INITHOOKS_PATH/bin/mysqlconf.py --user=concrete5-usr --pass="$PASSWORD"