#!/bin/bash -e
# Regen Concrete5 MySQL user random password

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF_PATH=/var/www/concrete5/config

echo "define('DB_PASSWORD', '"$PASSWORD"');" > $CONF_PATH/dbpass.php

# Backup site.php and create the new one
mv $CONF_PATH/site.php $CONF_PATH/oldsite.php
cp $CONF_PATH/blanksite.php $CONF_PATH/site.php
echo >> $CONF_PATH/site.php
cat $CONF_PATH/dbpass.php >> $CONF_PATH/site.php
# Adding the base url isn't needed as a firstboot as it's created later in the seque
# but just in case users regen the password, better to include it here too
cat $CONF_PATH/baseurl.php >> $CONF_PATH/site.php

$INITHOOKS_PATH/bin/mysqlconf.py --user=concrete5-usr --pass="$PASSWORD"