#!/bin/bash -e
# Concrete5 firstboot config file

# set Concrete5 admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/concrete5.py --pass="$APP_PASS" --email="$APP_EMAIL"
